### ISSUE TITLE
Install fatal error

### ISSUE THREAD

**Issue by fakeartist** [jcchavezs/cmb2-conditionals#11]
When I try to install the plugin I get the error:

Parse error: syntax error, unexpected ':' in C:\wamp\www\grid\wp-content\plugins\cmb2-conditionals\cmb2-conditionals.php on line 71

Is this a bug?

**Comment by jcchavezs** [comment]
Hi @fakeartist, which version of PHP so you have?

**Comment by fakeartist** [comment]
I have 5.2.5. I guess it's only compatible with PHP > 5.3, right?

**Comment by jcchavezs** [comment]
I can fix it for 5.2.5 as CMB2 has >5.2.4.

**Comment by jcchavezs** [comment]
@fakeartist done.

**Comment by fakeartist** [comment]
Fast and furious! I'm really impressed! Possibly the fastest ticket closed ever! Thanks a lot! Cheers
