### ISSUE TITLE
WP Coding standards and staying out of global namespace

### ISSUE THREAD

**Issue by jrfnl** [jcchavezs/cmb2-conditionals#16]
Hi José,

Would you be open to me changing the code to comply with the WordPress coding standards and to refactor the functions to a class ?

**Comment by jcchavezs** [comment]
@jrfnl that is something I have been thinking lately but I had no time for that. Feel free on doing it by a PR.

PS: My name is José Carlos.

**Comment by jrfnl** [comment]
My apologies, didn't mean to mangle your name. Forgive me.

**Comment by jrfnl** [comment]
As I was working on your code now anyway.... I got this sorted. Got a passing build ready for once the other PR (#17) has merged.
