### ISSUE TITLE
"let" statement in cmb2-conditionals.js

### ISSUE THREAD

**Issue by dameer** [jcchavezs/cmb2-conditionals#4]
The let keyword in Mozilla Firefox is only available to code blocks in HTML wrapped in a &lt;script type="application/javascript;version=1.7"&gt; block (or higher version).
...otherwise console will output an error.
Any replacement for "let" that is more close to the coding standards?

**Comment by ingageco** [comment]
Dameer - I solved this problem in FF by changing all instances of "let" to "var". @jcchavezs may be able to give some clarification to what this could affect, but currently everything seems to be working fine.

**Comment by dameer** [comment]
Yeap, I did that too and no problems thus far. Thanks!

**Comment by jcchavezs** [comment]
Hi @dameer @ingageco, I have replaces the usage of let in favor to "var" in order to fix the compatibility with old browsers.
