### ISSUE TITLE
Multiple conditions

### ISSUE THREAD

**Issue by ruturaaj** [jcchavezs/cmb2-conditionals#8]
Hi,

I'm facing problem in my scenario. The scenario is like this: Field 2 depends on the value of Field 1 AND Field 3 depends on the value of Field 2. So, eventually Field 3 depends on Field 2 (directly) and Field 1 (indirectly). 

With the current cmb2-conditionals, it toggles visibility of Field 2 with the condition on value of Field 1. However, the Field 3 is left visible even though its conditional field Field 2 is hidden. 

I hope I've phrased my scenario beyond confusion. Can someone please tell me if cmb2-conditionals is already capable of handling such scenarios? I see there is a "multiple conditional values" test-case is handled well by cmb2-conditionals; but not sure if it is capable of handling multiple conditional fields test-case as mentioned above.

Waiting for your reply...

Cheers,

Ruturaaj.

**Comment by ruturaaj** [comment]
Anybody to share solution/thoughts on this issue?

**Comment by jcchavezs** [comment]
Hi @ruturaaj, can you please post the configuration file for the fields so I can reproduce it in my local environment?

**Comment by jrfnl** [comment]
@ruturaaj @jcchavezs I ran into the same issue.

If I may summarize it - the fields display correctly based on the conditions. However the 'grand-child' field(s) don't *hide* correctly when the 'grand-parent' changes again.

I've included some code you could add to the example file to reproduce the issue.

If you click the checkbox, the radio set displays. If you then click on Option A or B, the text field displays.

However, if you *then* **_uncheck_** the checkbox, the radio set is correctly hidden, but the text field still shows while it should also be hidden..


```php
	$cmb_demo->add_field( array(
		'name' => 'Checkbox - do you want to show more fields ?',
		'id'   => $prefix . 'cascading-conditions-step1',
		'type' => 'checkbox',
	) );

	$cmb_demo->add_field( array(
		'name'             => 'Give me more, more, more!',
		'id'               => $prefix . 'cascading-conditions-step2',
		'type'             => 'radio',
		'show_option_none' => true,
		'options'          => array(
		    'a' => 'Option A',
		    'b' => 'Option B',
		),
		'attributes' => array(
			'data-conditional-id' => $prefix . 'cascading-conditions-step1',
			// works too: 'data-conditional-value' => 'on',
		)
	) );

	$cmb_demo->add_field( array(
		'name' => 'Option A detail',
		'id'   => $prefix . 'cascading-conditions-step3a',
		'type' => 'text',
		'attributes' => array(
			'required' => true, // Will be required only if visible.
			'data-conditional-id' => $prefix . 'cascading-conditions-step2',
			'data-conditional-value' => 'a',
		)
	) );
	
	$cmb_demo->add_field( array(
		'name' => 'Option B detail',
		'id'   => $prefix . 'cascading-conditions-step3b',
		'type' => 'text',
		'attributes' => array(
			'required' => true, // Will be required only if visible.
			'data-conditional-id' => $prefix . 'cascading-conditions-step2',
			'data-conditional-value' => 'b',
		)
	) );
```
